### ISSUE TITLE
soynlp관련 문서

### ISSUE THREAD

**Issue by min942773** [hyj378/EmojiRecommand#22]
[pycon2017koreannlp-170809135945.pdf](https://github.com/hyj378/ArtificialIntelligence/files/3252178/pycon2017koreannlp-170809135945.pdf)
soynlp 관련 내용은 27쪽부터 나와있습니다.

**Comment by kimkyeongnam** [comment]
https://colab.research.google.com/github/jiyoung-choi/TWL/blob/master/20180719_wordcloud
