### ISSUE TITLE
데이터 전처리

### ISSUE THREAD

**Issue by min942773** [hyj378/EmojiRecommand#25]
https://colab.research.google.com/drive/13eF9lBVJD0b1pzJgMSzMjVmI5uZom1iX
데이터 전처리 코드입니다.
original_csv 에는 여러분이 크롤링한 자료
preprocessed 특수문자 뺀 것 저장할 이름
eng_ver 번역한 것 저장할 이름
써주시면 됩니다~~~
참고로 완전 오래걸리니까 켜놓고 주무시는게 좋을 것 같아요...ㅎㅎ

**Comment by kimkyeongnam** [comment]
슬픔
* [원본](https://drive.google.com/file/d/1Ezpda2Mk6cQgce71AVe6DnPZs19Up_io/view?usp=sharing)
* [@제거](https://drive.google.com/file/d/1WEmtFDzCCtoxFD8l344fPytddAz61JRV/view?usp=sharing)
* [영어번역](https://drive.google.com/file/d/1EtQu1nO2YyDL6ZzbKjoYBWnjUBlAvxpE/view?usp=sharing)

**Comment by min942773** [comment]
데이터 전처리를 코랩에서 하는 것보다 주피터노트북으로 하는 것이 훨씬 빨라서 주피터 노트북에서 사용할 코드를 올립니다!!
대신 코드의 저장 장소와 같은 위치에 크롤링 파일이 있어야합니당~
[데이터 전처리.zip](https://github.com/hyj378/ArtificialIntelligence/files/3274671/default.zip)

**Comment by hyj378** [comment]
원래보다 자료가 반토막 나기는 했지만 양은 충분할것같아서 일단 올려유ㅜㅜ
[한국어 처리 후](https://drive.google.com/file/d/184sKeb7h37G5OKzM-knZZd0NnElGe_XD/view?usp=sharing)

**Comment by jiin0217** [comment]
전처리파일일
[ANGRY_data_no_@.zip](https://github.com/hyj378/ArtificialIntelligence/files/3281371/ANGRY_data_no_%40.zip)

**Comment by zero5two4** [comment]
'애정' 데이터 전처리 결과물(21933개)
https://drive.google.com/open?id=1qIIZB2ugB8QK1sG-hM9ZodDdiT-ijzGX

**Comment by min942773** [comment]
'피곤' 전처리 결과물
35554개

[tired_processed.zip](https://github.com/hyj378/ArtificialIntelligence/files/3281646/tired_processed.zip)
